name: ModDisable
main: org.shybella.ModDisable
softdepend: [Multiverse-Core, My Worlds, Transporter, MystCraft]
version: 3.0
commands:
   blockinfo:
      description: Provides type ID and damage information for a material in the world or in hand.
      usage: /BlockInfo
      permission: moddisable.blockinfo   
   moddisablereload:
      description: Reloads the banned item list from the config file.
      usage: /moddisablereload
      permission: moddisable.reload
permissions:
    moddisable.admin.*:
        description: Grants all administrative privileges.
        children:
            moddisable.blockinfo: true
            moddisable.reload: true
    moddisable.*:
        description: Grants permission to bypass all bans.
        default: op
    moddisable.blockinfo:
        description: Grants permission to use /BlockInfo.
        default: op
    moddisable.reload:
        description: Grants permission to use /ModDisableReload.
        default: op